### ISSUE TITLE
使用出错pages must contain at least 1 page.

### ISSUE THREAD

**Issue by mmdlsu** [edwinhuish/uni-macros#9]
[uni-app] Error: pages.json->pages must contain at least 1 page.
![image](https://github.com/user-attachments/assets/7eaa0c98-c1d2-43b8-aef3-35803848e489)
![image](https://github.com/user-attachments/assets/84552c46-d9a4-4a14-922e-96e5e306b54d)

**Comment by edwinhuish** [comment]
这个是uniapp的限制，而且一个uniapp至少也得有一个页面，不是吗？

**Comment by mmdlsu** [comment]
我所测试的是你当前项目中的playground，它没有自动生成pages路径啊？，正常不是所有的 page 都会被自动发现？

**Comment by mmdlsu** [comment]
> 我所测试的是你当前项目中的playground，它没有自动生成pages路径啊？，正常不是所有的 page 都会被自动发现？

![image](https://github.com/user-attachments/assets/a3a97856-b284-470e-80c5-8d2492b2c88b)

**Comment by edwinhuish** [comment]
请问你是怎么执行的？这边重新执行 `pnpm --filter ./packages/playground/ dev:h5` 能够正确生成 `pages.json`，未发现你所说的问题。

请提供详细重现步骤。

**Comment by edwinhuish** [comment]
大概知道你的问题是怎么出现的了。你只需要删掉 `pages.json` 并重新运行即可。

`pages.json` 是最终文件，你不应编辑它，也不要手动删除 `pages` 的元素。如果你有额外数据需要添加，请添加在 `pages.json.ts` 里。

**Comment by mmdlsu** [comment]
我是单独把playground移出来运行，并修改"vite-plugin-pages-json": "workspace:^"为"vite-plugin-pages-json": "^0.0.10"
删掉 pages.json然后运行：pnpm run dev:mp-weixin还是不行

**Comment by edwinhuish** [comment]
已修复。

**Comment by edwinhuish** [comment]
已修复
